### ISSUE TITLE
ca.mcgill.sable:soot:jar:3.0.0-20171109.123005-225 no longer available.

### ISSUE THREAD

**Issue by SeriousSnail** [xiaofen9/SVHunter#1]
Hello everyone,

In order to build SVHunter-Tracer I have run this command : 

_mvn package -f ._

This is the error message that I obtain : 

> [ERROR] Failed to execute goal on project SVHunter-Tracer: Could not resolve dependencies for project org.ieee-security:SVHunter-Tracer:jar:0.1-SNAPSHOT: Failure to find ca.mcgill.sable:soot:jar:3.0.0-20171109.123005-225 in https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of soot-snapshot has elapsed or updates are forced

It appears that ca.mcgill.sable:soot:jar:3.0.0-20171109.123005-225 does not exist anymore. 
Following the same link I have found that only the 3.0.0-20180416.152636-309 still exist wich doesn't work.

Is there any other possiblity to build SVHunter-Tracer unsing mvn ?

**Comment by xiaofen9** [comment]
Thanks for trying out our tool. I am looking into this issue.

**Comment by xiaofen9** [comment]
Thanks for your patience. It turns out that the dependency repo is having some trouble so the package is missing.
I have invited my collaborator who is in charge of this part. He will be helping you update the dependency.

**Comment by xiaofen9** [comment]
Hi,

We have updated SVHunter with a newer version soot lib. Now you should be able to compile it. Note that we found the soot upgrade changes part of the tracing result. We are looking into this issue right now.
